development:
    adapter: postgresql
    encoding: unicode
    database: betbuilder
    pool: 5
    username: postgres
    password:

production:
  adapter: postgresql
  encoding: unicode
  database: betbuilder
  pool: 5
  username: postgres
  password: